### PR TITLE
Changed HTTP library from urllib2 to requests

### PR DESCRIPTION
**Pull request by gu1ll0me**
Many changes to introduce the Requests library.

http://requests.readthedocs.org/en/latest/
https://gist.github.com/kennethreitz/973705

### CODE REVIEW

**Comment by rshipp** [comment]
:+1: 
@Inkane, @Ram-Z ?

**Comment by Inkane** [comment]
@michaudg : Are you really sure that the context manager protocol will still work if you change the signature of the `__exit__` method? IMHO that should break.

**Comment by gu1ll0me** [comment]
You're right, i will revert that.

**Comment by Ram-Z** [comment]
I don't know enough python to judge this, so it's up to you guys ;)

**Comment by Inkane** [comment]
Once `__exit__` works again: Ship it!

**Pull request merged**
